name: 'Genropy Docker Build and Push'
description: 'Build and push Docker images of a Genropy project'
author: 'genropy'

inputs:
  image_name:
    description: 'Name of the Docker image'
    required: true
  instance_name:
    description: 'Instance name for genropy'
    required: true
  registry:
    description: 'Container registry URL'
    required: false
    default: 'ghcr.io'
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  org_clone_token:
    description: 'Token for cloning private repositories'
    required: true
  github_token:
    description: 'GitHub token for registry authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install genropy
      shell: bash
      run: |
        pip install git+https://github.com/genropy/genropy.git@develop#subdirectory=gnrpy
        gnr app initgenropy
        gnr core bagedit /home/runner/.gnr/environment.xml add projects.build path=/home/runner/work/${{ github.event.repository.name }}

    - name: Log in to Container Registry
      shell: bash
      run: |
        echo "${{ inputs.github_token }}" | docker login ${{ inputs.registry }} \
        -u "${{ github.actor }}" --password-stdin

    - name: Configure git auth header and run builder
      shell: bash
      env:
        ORG_CLONE_TOKEN: ${{ inputs.org_clone_token }}
      run: |
        set -euo pipefail
        export GNR_LOGLEVEL=debug
        export GIT_TERMINAL_PROMPT=0
        export GIT_CONFIG_GLOBAL="$RUNNER_TEMP/gitconfig_with_pat"

        cat > "$GIT_CONFIG_GLOBAL" <<'EOF'
        [url "https://github.com/"]
          insteadOf = git@github.com:
          insteadOf = ssh://git@github.com/
        EOF

        git config --global --unset-all http.https://github.com/.extraheader || true
        git config --global http.https://github.com/.extraheader \
        "AUTHORIZATION: basic $(printf "x-access-token:%s" "$ORG_CLONE_TOKEN" | base64 -w0)"

        gnr app dockerize  -n ${{ inputs.image_name }} ${{ inputs.instance_name }}

    - name: Tag and push
      shell: bash
      run: |
        IMAGE=${{ inputs.registry }}/${{ github.repository }}:latest
        docker push "$IMAGE"

branding:
  icon: 'package'
  color: 'blue'
